import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Team Collabera
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>- ram - </code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Rose-Ann &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ligula eget blandit egestas. Mauris egestas elit ac nunc sagittis vehicula. Nullam maximus, metus nec rutrum semper, augue tortor dictum eros, vitae consectetur elit magna a quam. Aenean pulvinar sed sapien bibendum posuere.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Peter &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ligula eget blandit egestas. Mauris egestas elit ac nunc sagittis vehicula. Nullam maximus, metus nec rutrum semper, augue tortor dictum eros, vitae consectetur elit magna a quam. Aenean pulvinar sed sapien bibendum posuere.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Popoy &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ligula eget blandit egestas. Mauris egestas elit ac nunc sagittis vehicula. Nullam maximus, metus nec rutrum semper, augue tortor dictum eros, vitae consectetur elit magna a quam. Aenean pulvinar sed sapien bibendum posuere.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Alvin &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ligula eget blandit egestas. Mauris egestas elit ac nunc sagittis vehicula. Nullam maximus, metus nec rutrum semper, augue tortor dictum eros, vitae consectetur elit magna a quam. Aenean pulvinar sed sapien bibendum posuere.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Dindin &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ligula eget blandit egestas. Mauris egestas elit ac nunc sagittis vehicula. Nullam maximus, metus nec rutrum semper, augue tortor dictum eros, vitae consectetur elit magna a quam. Aenean pulvinar sed sapien bibendum posuere.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Donna &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ligula eget blandit egestas. Mauris egestas elit ac nunc sagittis vehicula. Nullam maximus, metus nec rutrum semper, augue tortor dictum eros, vitae consectetur elit magna a quam. Aenean pulvinar sed sapien bibendum posuere.</p>
          </a>
          
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Adrian &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ligula eget blandit egestas. Mauris egestas elit ac nunc sagittis vehicula. Nullam maximus, metus nec rutrum semper, augue tortor dictum eros, vitae consectetur elit magna a quam. Aenean pulvinar sed sapien bibendum posuere.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Carl &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ligula eget blandit egestas. Mauris egestas elit ac nunc sagittis vehicula. Nullam maximus, metus nec rutrum semper, augue tortor dictum eros, vitae consectetur elit magna a quam. Aenean pulvinar sed sapien bibendum posuere.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Niño &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ligula eget blandit egestas. Mauris egestas elit ac nunc sagittis vehicula. Nullam maximus, metus nec rutrum semper, augue tortor dictum eros, vitae consectetur elit magna a quam. Aenean pulvinar sed sapien bibendum posuere.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Gio &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ligula eget blandit egestas. Mauris egestas elit ac nunc sagittis vehicula. Nullam maximus, metus nec rutrum semper, augue tortor dictum eros, vitae consectetur elit magna a quam. Aenean pulvinar sed sapien bibendum posuere.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Justine &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ligula eget blandit egestas. Mauris egestas elit ac nunc sagittis vehicula. Nullam maximus, metus nec rutrum semper, augue tortor dictum eros, vitae consectetur elit magna a quam. Aenean pulvinar sed sapien bibendum posuere.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
